import type { SourceExtensionSummary } from './source-extensions'

// Trusted release metadata only. Original source snapshots and private backup data are not shipped.
export const builtinFeatureKeys = [
  'extension-backups',
  'header-minimal',
  'project-thread-navigation',
  'thread-attachments',
  'compact-branding',
  'message-queue',
  'sidebar-resizing',
  'workspace-surfaces',
  'message-navigation',
  'surface-layout',
  'compact-workspace',
  'sidebar-spacing',
  'compact-thread-activity',
  'project-colors',
  'thread-arrangement',
  'compact-badges',
  'provider-artwork',
  'centered-badges',
  'thread-git-metadata',
  'sidebar-footer',
  'chrome-polish',
  'collapsed-branding',
  'hide-version',
  'header-action-spacing',
  'individual-arrange-controls',
  'composer-shape',
  'composer-action-style',
  'composer-spacing',
  'composer-compact',
  'navigation-names',
  'compact-attachments',
  'compact-source-cards',
  'project-map',
  'research-workbench',
  'header-view-layout',
  'claude-brand-color',
  'research-fullheight',
  'research-goal-controls',
  'persistent-drafts',
  'research-filters',
  'builtin-management-shortcut',
] as const
export type BuiltinFeatureKey = (typeof builtinFeatureKeys)[number]

export interface BuiltinExtensionDefinition {
  id: string
  originalId: string
  name: string
  description: string
  version: string
  createdAt: string
  updatedAt: string
  files: string[]
  features: readonly BuiltinFeatureKey[]
  effect: string
}

export const builtinExtensionCatalog: readonly BuiltinExtensionDefinition[] = [
  {
    id: 'builtin-source-9bb3ffbcce4d',
    originalId: 'source-9bb3ffbcce4d',
    name: 'Add a complete downloadable backup for all installed runtime and source extensions',
    description:
      'Add a complete downloadable backup for all installed runtime and source extensions',
    version: '1.0.0',
    createdAt: '2026-10-08T23:51:17.118Z',
    updatedAt: '2026-10-08T23:51:17.118Z',
    files: ['src/renderer/components/ExtensionDialog.tsx'],
    features: ['extension-backups'],
    effect: 'Turning this extension off disables the full extension-backup export shortcut.',
  },
  {
    id: 'builtin-source-a80581604688',
    originalId: 'source-a80581604688',
    name: 'Remove the Research workspace label from the top bar',
    description: 'Remove the Research workspace label from the top bar',
    version: '1.0.0',
    createdAt: '2026-10-08T19:14:08.734Z',
    updatedAt: '2026-10-08T19:14:08.734Z',
    files: ['src/renderer/components/TitleBar.tsx'],
    features: ['header-minimal'],
    effect: 'Turning this extension off disables minimal workspace title.',
  },
  {
    id: 'builtin-source-73b7de289714',
    originalId: 'source-73b7de289714',
    name: 'Group sidebar threads by project',
    description: 'Group sidebar threads by project',
    version: '1.0.0',
    createdAt: '2026-10-08T19:19:41.192Z',
    updatedAt: '2026-10-08T19:19:41.192Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/SidebarProjectThreads.tsx',
      'src/renderer/components/sidebar-project-threads.css',
    ],
    features: ['project-thread-navigation'],
    effect:
      'Turning this extension off disables project grouping, searching, filtering and sorting.',
  },
  {
    id: 'builtin-source-2c5d2001c41c',
    originalId: 'source-2c5d2001c41c',
    name: 'Add image and file attachments to threads',
    description: 'Add image and file attachments to threads',
    version: '1.0.0',
    createdAt: '2026-10-08T19:37:03.090Z',
    updatedAt: '2026-10-08T19:37:03.090Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/attachments.ts',
      'src/renderer/components/MessageView.tsx',
      'src/renderer/components/ThreadAttachments.tsx',
      'src/renderer/components/thread-attachments.css',
      'src/renderer/state.ts',
    ],
    features: ['thread-attachments'],
    effect:
      'Turning this extension off disables new file selection and uploads (saved files remain accessible).',
  },
  {
    id: 'builtin-source-1f744fc8d6d7',
    originalId: 'source-1f744fc8d6d7',
    name: 'Unify Life branding at the top of the sidebar and add search, project and thread actions, filters, and sorting',
    description:
      'Unify Life branding at the top of the sidebar and add search, project and thread actions, filters, and sorting',
    version: '1.0.0',
    createdAt: '2026-10-08T20:07:39.344Z',
    updatedAt: '2026-10-08T20:07:39.344Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/SidebarProjectThreads.tsx',
      'src/renderer/components/SidebarProjects.tsx',
      'src/renderer/components/TitleBar.tsx',
      'src/renderer/components/sidebar-navigation.css',
    ],
    features: ['project-thread-navigation', 'compact-branding'],
    effect:
      'Turning this extension off disables project grouping, searching, filtering and sorting, compact Life branding.',
  },
  {
    id: 'builtin-source-7ae6e7db5cdd',
    originalId: 'source-7ae6e7db5cdd',
    name: 'Refine life. branding and thread layout, align sidebar icons, and support queued follow-ups with adjustable run settings',
    description:
      'Refine life. branding and thread layout, align sidebar icons, and support queued follow-ups with adjustable run settings',
    version: '1.0.0',
    createdAt: '2026-10-08T20:35:56.873Z',
    updatedAt: '2026-10-08T20:35:56.873Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/QueuedMessages.tsx',
      'src/renderer/components/TitleBar.tsx',
      'src/renderer/state.ts',
      'src/renderer/thread-queue.ts',
      'src/renderer/thread-refinements.css',
    ],
    features: ['message-queue', 'compact-branding'],
    effect:
      'Turning this extension off disables queued follow-ups (saved queue entries remain recoverable), compact Life branding.',
  },
  {
    id: 'builtin-source-e143e0e038ea',
    originalId: 'source-e143e0e038ea',
    name: 'Add resizable sidebars, tabbed workspace surfaces with a full-height divider, thread message navigation, and subtler use',
    description:
      'Add resizable sidebars, tabbed workspace surfaces with a full-height divider, thread message navigation, and subtler user message bubbles',
    version: '1.0.0',
    createdAt: '2026-10-08T21:00:27.898Z',
    updatedAt: '2026-10-08T21:00:27.898Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/BrowserSurface.tsx',
      'src/renderer/components/MessageView.tsx',
      'src/renderer/components/PullRequestSurface.tsx',
      'src/renderer/components/RemoteTerminal.tsx',
      'src/renderer/components/SidebarResize.tsx',
      'src/renderer/components/ThreadMessageNavigator.tsx',
      'src/renderer/components/TitleBar.tsx',
      'src/renderer/components/WorkspacePanel.tsx',
      'src/renderer/components/WorkspaceSurfaces.tsx',
      'src/renderer/components/workspace-surfaces.css',
    ],
    features: ['sidebar-resizing', 'workspace-surfaces', 'message-navigation'],
    effect:
      'Turning this extension off disables sidebar resize controls, workspace surfaces and their background operations, message search and navigator.',
  },
  {
    id: 'builtin-source-8390092f925a',
    originalId: 'source-8390092f925a',
    name: 'Widen and tighten the surface picker, remove the Workspace heading, and match the right header background to the sidebar',
    description:
      'Widen and tighten the surface picker, remove the Workspace heading, and match the right header background to the sidebar',
    version: '1.0.0',
    createdAt: '2026-10-08T21:05:53.849Z',
    updatedAt: '2026-10-08T21:05:53.849Z',
    files: [
      'src/renderer/components/WorkspaceSurfaces.tsx',
      'src/renderer/components/workspace-surfaces.css',
    ],
    features: ['surface-layout'],
    effect: 'Turning this extension off disables compact surface picker styling.',
  },
  {
    id: 'builtin-source-bc725feec6fa',
    originalId: 'source-bc725feec6fa',
    name: "Shorten the application header, center and tighten the message navigator, and use only the left sidebar's outer padding",
    description:
      "Shorten the application header, center and tighten the message navigator, and use only the left sidebar's outer padding",
    version: '1.0.0',
    createdAt: '2026-10-08T21:14:28.125Z',
    updatedAt: '2026-10-08T21:14:28.125Z',
    files: ['src/renderer/compact-workspace.css', 'src/renderer/thread-refinements.css'],
    features: ['compact-workspace'],
    effect: 'Turning this extension off disables compact header and workspace spacing.',
  },
  {
    id: 'builtin-source-8e17df5a7830',
    originalId: 'source-8e17df5a7830',
    name: 'Restore the previous left sidebar padding and spacing',
    description: 'Restore the previous left sidebar padding and spacing',
    version: '1.0.0',
    createdAt: '2026-10-08T21:18:09.691Z',
    updatedAt: '2026-10-08T21:18:09.691Z',
    files: ['src/renderer/compact-workspace.css'],
    features: ['sidebar-spacing'],
    effect: 'Turning this extension off disables compact sidebar padding.',
  },
  {
    id: 'builtin-source-d14e8c229403',
    originalId: 'source-d14e8c229403',
    name: 'Refine project and Life threads with compact activity summaries, faster attachments, project-colored badges, and configu',
    description:
      'Refine project and Life threads with compact activity summaries, faster attachments, project-colored badges, and configurable sidebar arrangements',
    version: '1.0.0',
    createdAt: '2026-10-08T21:39:48.429Z',
    updatedAt: '2026-10-08T21:39:48.429Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/attachments.ts',
      'src/renderer/components/SidebarProjectThreads.tsx',
      'src/renderer/components/SidebarProjects.tsx',
      'src/renderer/components/SidebarThread.tsx',
      'src/renderer/components/ThreadBadge.tsx',
      'src/renderer/components/ThreadTimeline.tsx',
      'src/renderer/components/thread-experience.css',
      'src/renderer/sidebar-ordering.ts',
      'src/renderer/state.ts',
      'src/renderer/thread-activity.ts',
    ],
    features: ['compact-thread-activity', 'project-colors', 'thread-arrangement'],
    effect:
      'Turning this extension off disables grouped activity presentation, project color assignment, Snooze and Settle controls and sleeping-thread filtering.',
  },
  {
    id: 'builtin-source-df30d8af2e48',
    originalId: 'source-df30d8af2e48',
    name: 'Slightly taller header and smaller thread badges with project initials',
    description: 'Slightly taller header and smaller thread badges with project initials',
    version: '1.0.0',
    createdAt: '2026-10-08T21:46:34.239Z',
    updatedAt: '2026-10-08T21:46:34.239Z',
    files: [
      'src/renderer/compact-workspace.css',
      'src/renderer/components/ThreadBadge.tsx',
      'src/renderer/components/thread-experience.css',
    ],
    features: ['compact-badges'],
    effect: 'Turning this extension off disables compact thread badges.',
  },
  {
    id: 'builtin-source-b4b5867cc0cc',
    originalId: 'source-b4b5867cc0cc',
    name: 'Match reference thread activity, add live working status and SVGL provider logos, center project badges, and animate nei',
    description:
      'Match reference thread activity, add live working status and SVGL provider logos, center project badges, and animate neighboring navigation ticks',
    version: '1.0.0',
    createdAt: '2026-10-08T22:00:52.073Z',
    updatedAt: '2026-10-08T22:00:52.073Z',
    files: [
      'src/renderer/assets/svgl/openai.svg',
      'src/renderer/components/Icons.tsx',
      'src/renderer/components/MessageView.tsx',
      'src/renderer/components/SidebarThread.tsx',
      'src/renderer/components/ThreadActivityRows.tsx',
      'src/renderer/components/ThreadBadge.tsx',
      'src/renderer/components/ThreadMessageNavigator.tsx',
      'src/renderer/components/ThreadRunStatus.tsx',
      'src/renderer/components/ThreadTimeline.tsx',
      'src/renderer/components/thread-experience.css',
      'src/renderer/components/workspace-surfaces.css',
    ],
    features: [
      'compact-thread-activity',
      'provider-artwork',
      'centered-badges',
      'message-navigation',
    ],
    effect:
      'Turning this extension off disables grouped activity presentation, provider logo artwork, centered badge alignment, message search and navigator.',
  },
  {
    id: 'builtin-source-d39f6c57b8d7',
    originalId: 'source-d39f6c57b8d7',
    name: 'Restore visible OpenAI and Claude logos using inline SVG artwork',
    description: 'Restore visible OpenAI and Claude logos using inline SVG artwork',
    version: '1.0.0',
    createdAt: '2026-10-08T22:09:33.818Z',
    updatedAt: '2026-10-08T22:09:33.818Z',
    files: [
      'src/renderer/components/Icons.tsx',
      'src/renderer/components/thread-experience.css',
      'src/renderer/provider-artwork.ts',
    ],
    features: ['provider-artwork'],
    effect: 'Turning this extension off disables provider logo artwork.',
  },
  {
    id: 'builtin-source-38077381109d',
    originalId: 'source-38077381109d',
    name: 'Refine thread controls with OpenAI branding, custom run selectors, branch and cloud metadata, hover details, Settle and',
    description:
      'Refine thread controls with OpenAI branding, custom run selectors, branch and cloud metadata, hover details, Settle and snooze actions, and immediate attachment uploads',
    version: '1.0.0',
    createdAt: '2026-10-08T22:26:00.539Z',
    updatedAt: '2026-10-08T22:26:00.539Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/Icons.tsx',
      'src/renderer/components/RunSelectors.tsx',
      'src/renderer/components/SidebarProjectThreads.tsx',
      'src/renderer/components/SidebarProjects.tsx',
      'src/renderer/components/SidebarThread.tsx',
      'src/renderer/components/ThreadAttachments.tsx',
      'src/renderer/components/thread-controls.css',
      'src/renderer/draft-upload.ts',
      'src/renderer/state.ts',
      'src/renderer/thread-metadata.ts',
    ],
    features: ['thread-git-metadata', 'thread-arrangement'],
    effect:
      'Turning this extension off disables automatic branch and pull-request metadata refresh, Snooze and Settle controls and sleeping-thread filtering.',
  },
  {
    id: 'builtin-source-94638dc56d1e',
    originalId: 'source-94638dc56d1e',
    name: 'Refine sidebar search and spacing, pin Settled above footer tools, remove the machine card, and move Collapse to the bot',
    description:
      'Refine sidebar search and spacing, pin Settled above footer tools, remove the machine card, and move Collapse to the bottom right',
    version: '1.0.0',
    createdAt: '2026-10-08T22:40:41.499Z',
    updatedAt: '2026-10-08T22:40:41.499Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/SidebarProjects.tsx',
      'src/renderer/components/TitleBar.tsx',
      'src/renderer/components/sidebar-footer-layout.css',
    ],
    features: ['sidebar-footer'],
    effect: 'Turning this extension off disables compact footer arrangement.',
  },
  {
    id: 'builtin-source-f4c0f424ebf0',
    originalId: 'source-f4c0f424ebf0',
    name: 'Polish Life branding, collapsed sidebar, project headers, workspace controls, and conversation alignment',
    description:
      'Polish Life branding, collapsed sidebar, project headers, workspace controls, and conversation alignment',
    version: '1.0.0',
    createdAt: '2026-10-08T22:55:34.313Z',
    updatedAt: '2026-10-08T22:55:34.313Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/SidebarResize.tsx',
      'src/renderer/components/ThreadMessageNavigator.tsx',
      'src/renderer/components/TitleBar.tsx',
      'src/renderer/components/WorkspaceSurfaces.tsx',
      'src/renderer/components/life-chrome-polish.css',
    ],
    features: ['chrome-polish'],
    effect: 'Turning this extension off disables polished compact chrome styling.',
  },
  {
    id: 'builtin-source-2846644351b9',
    originalId: 'source-2846644351b9',
    name: 'Move collapsed Life branding beside Expand at the bottom and reclaim the left rail for the header and conversation',
    description:
      'Move collapsed Life branding beside Expand at the bottom and reclaim the left rail for the header and conversation',
    version: '1.0.0',
    createdAt: '2026-10-08T23:04:36.632Z',
    updatedAt: '2026-10-08T23:04:36.632Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/TitleBar.tsx',
      'src/renderer/components/collapsed-brand-footer.css',
    ],
    features: ['collapsed-branding'],
    effect: 'Turning this extension off disables bottom collapsed-rail branding.',
  },
  {
    id: 'builtin-source-de08b7661bb6',
    originalId: 'source-de08b7661bb6',
    name: 'Remove the product version from the top header',
    description: 'Remove the product version from the top header',
    version: '1.0.0',
    createdAt: '2026-10-08T23:05:12.639Z',
    updatedAt: '2026-10-08T23:05:12.639Z',
    files: ['src/renderer/App.tsx'],
    features: ['hide-version'],
    effect: 'Turning this extension off disables hidden header version.',
  },
  {
    id: 'builtin-source-7fe231a4b39b',
    originalId: 'source-7fe231a4b39b',
    name: 'Keep the three-dot menu rightmost and unify spacing between sidebar, theme, and thread controls',
    description:
      'Keep the three-dot menu rightmost and unify spacing between sidebar, theme, and thread controls',
    version: '1.0.0',
    createdAt: '2026-10-08T23:10:21.342Z',
    updatedAt: '2026-10-08T23:10:21.342Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/TitleBar.tsx',
      'src/renderer/components/WorkspaceSurfaces.tsx',
      'src/renderer/components/header-action-spacing.css',
    ],
    features: ['header-action-spacing'],
    effect: 'Turning this extension off disables compact header action spacing.',
  },
  {
    id: 'builtin-source-7872447a26e1',
    originalId: 'source-7872447a26e1',
    name: 'Highlight Snooze and Settle individually instead of their shared group',
    description: 'Highlight Snooze and Settle individually instead of their shared group',
    version: '1.0.0',
    createdAt: '2026-10-08T23:13:02.658Z',
    updatedAt: '2026-10-08T23:13:02.658Z',
    files: ['src/renderer/components/thread-controls.css'],
    features: ['individual-arrange-controls'],
    effect: 'Turning this extension off disables individual Snooze and Settle highlights.',
  },
  {
    id: 'builtin-source-5066db7ba3f3',
    originalId: 'source-5066db7ba3f3',
    name: 'Restore the three-dot menu outside the workspace sidebar with consistent control spacing',
    description:
      'Restore the three-dot menu outside the workspace sidebar with consistent control spacing',
    version: '1.0.0',
    createdAt: '2026-10-08T23:14:52.566Z',
    updatedAt: '2026-10-08T23:14:52.566Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/TitleBar.tsx',
      'src/renderer/components/header-action-spacing.css',
    ],
    features: ['header-action-spacing'],
    effect: 'Turning this extension off disables compact header action spacing.',
  },
  {
    id: 'builtin-source-0dc6197e23cf',
    originalId: 'source-0dc6197e23cf',
    name: 'Match the reference composer with a rounded input, compact run controls, circular actions, and inset workspace tray',
    description:
      'Match the reference composer with a rounded input, compact run controls, circular actions, and inset workspace tray',
    version: '1.0.0',
    createdAt: '2026-10-08T23:21:09.401Z',
    updatedAt: '2026-10-08T23:21:09.401Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/ReferenceComposer.tsx',
      'src/renderer/components/reference-composer.css',
    ],
    features: ['composer-shape'],
    effect: 'Turning this extension off disables reference composer styling.',
  },
  {
    id: 'builtin-source-b1de0fc7acc3',
    originalId: 'source-b1de0fc7acc3',
    name: 'Refine the permission menu, use transparent blue Send and red Stop controls, and reduce composer bottom spacing',
    description:
      'Refine the permission menu, use transparent blue Send and red Stop controls, and reduce composer bottom spacing',
    version: '1.0.0',
    createdAt: '2026-10-08T23:32:25.168Z',
    updatedAt: '2026-10-08T23:32:25.168Z',
    files: [
      'src/renderer/components/ReferenceComposer.tsx',
      'src/renderer/components/collapsed-brand-footer.css',
      'src/renderer/components/reference-composer.css',
    ],
    features: ['composer-action-style'],
    effect: 'Turning this extension off disables colored Send and Stop styling.',
  },
  {
    id: 'builtin-source-56303aa9af08',
    originalId: 'source-56303aa9af08',
    name: 'Restore workspace tray and outer spacing while retaining reduced bottom padding inside the main input',
    description:
      'Restore workspace tray and outer spacing while retaining reduced bottom padding inside the main input',
    version: '1.0.0',
    createdAt: '2026-10-08T23:35:37.440Z',
    updatedAt: '2026-10-08T23:35:37.440Z',
    files: [
      'src/renderer/components/collapsed-brand-footer.css',
      'src/renderer/components/reference-composer.css',
    ],
    features: ['composer-spacing'],
    effect: 'Turning this extension off disables compact composer outer spacing.',
  },
  {
    id: 'builtin-source-031b0e38170a',
    originalId: 'source-031b0e38170a',
    name: 'Reduce main input padding and action spacing, lighten Send, and brighten the attachment icon on hover',
    description:
      'Reduce main input padding and action spacing, lighten Send, and brighten the attachment icon on hover',
    version: '1.0.0',
    createdAt: '2026-10-08T23:39:55.296Z',
    updatedAt: '2026-10-08T23:39:55.296Z',
    files: ['src/renderer/components/reference-composer.css'],
    features: ['composer-compact'],
    effect: 'Turning this extension off disables compact composer inner spacing.',
  },
  {
    id: 'builtin-source-e29be4176e7b',
    originalId: 'source-e29be4176e7b',
    name: 'Rename navigation to Map and Agents and give port forwarding a distinct cable icon',
    description:
      'Rename navigation to Map and Agents and give port forwarding a distinct cable icon',
    version: '1.0.0',
    createdAt: '2026-10-08T23:44:39.555Z',
    updatedAt: '2026-10-08T23:44:39.555Z',
    files: ['src/renderer/App.tsx', 'src/renderer/components/TitleBar.tsx'],
    features: ['navigation-names'],
    effect: 'Turning this extension off disables Map and Agents navigation labels.',
  },
  {
    id: 'builtin-source-291e3f4359ea',
    originalId: 'source-291e3f4359ea',
    name: 'Compact user messages and square image previews with remove buttons and upload progress overlays',
    description:
      'Compact user messages and square image previews with remove buttons and upload progress overlays',
    version: '1.0.0',
    createdAt: '2026-10-09T03:03:25.752Z',
    updatedAt: '2026-10-09T03:03:25.752Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/MessageView.tsx',
      'src/renderer/components/ThreadAttachments.tsx',
      'src/renderer/components/message-attachment-layout.css',
    ],
    features: ['compact-attachments'],
    effect: 'Turning this extension off disables compact attachment and user-message styling.',
  },
  {
    id: 'builtin-source-265a22e310cd',
    originalId: 'source-265a22e310cd',
    name: 'Compact Life change cards, smaller image previews, and unique project colors',
    description: 'Compact Life change cards, smaller image previews, and unique project colors',
    version: '1.0.0',
    createdAt: '2026-10-09T03:35:16.170Z',
    updatedAt: '2026-10-09T03:35:16.170Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/LifeSourceCard.tsx',
      'src/renderer/components/MessageView.tsx',
      'src/renderer/components/ProjectColors.tsx',
      'src/renderer/components/ThreadBadge.tsx',
      'src/renderer/components/life-source-card.css',
      'src/renderer/components/thread-presentation-attachments.css',
      'src/renderer/source-presentation.ts',
      'src/renderer/state.ts',
    ],
    features: ['compact-source-cards', 'project-colors'],
    effect:
      'Turning this extension off disables compact customization source cards, project color assignment.',
  },
  {
    id: 'builtin-source-ee937ac6bc82',
    originalId: 'source-ee937ac6bc82',
    name: 'Life project map and Research goals with problem workspaces',
    description: 'Life project map and Research goals with problem workspaces',
    version: '1.0.0',
    createdAt: '2026-10-09T04:26:09.585Z',
    updatedAt: '2026-10-09T04:26:09.585Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/GraphCanvas.tsx',
      'src/renderer/components/LifeMap.tsx',
      'src/renderer/components/ProjectColors.tsx',
      'src/renderer/components/ResearchWorkbench.tsx',
      'src/renderer/components/TitleBar.tsx',
      'src/renderer/components/life-workbench.css',
      'src/renderer/workbench.ts',
    ],
    features: ['project-map', 'research-workbench'],
    effect:
      'Turning this extension off disables the project map and its lifecycle, research navigation, machine synchronization and workspace lifecycle.',
  },
  {
    id: 'builtin-source-12cfab44e306',
    originalId: 'source-12cfab44e306',
    name: 'Fix overlapping Map, Agents, and Research controls in the header',
    description: 'Fix overlapping Map, Agents, and Research controls in the header',
    version: '1.0.0',
    createdAt: '2026-10-09T04:33:31.841Z',
    updatedAt: '2026-10-09T04:33:31.841Z',
    files: [
      'src/renderer/components/TitleBar.tsx',
      'src/renderer/components/header-view-switch.css',
      'src/renderer/components/life-workbench.css',
    ],
    features: ['header-view-layout'],
    effect: 'Turning this extension off disables compact header view-switch styling.',
  },
  {
    id: 'builtin-source-2b3a5bff463a',
    originalId: 'source-2b3a5bff463a',
    name: 'Use Claude’s terracotta brand color for its logo',
    description: 'Use Claude’s terracotta brand color for its logo',
    version: '1.0.0',
    createdAt: '2026-10-09T04:41:07.813Z',
    updatedAt: '2026-10-09T04:41:07.813Z',
    files: ['src/renderer/components/Icons.tsx'],
    features: ['claude-brand-color'],
    effect: 'Turning this extension off disables Claude terracotta artwork.',
  },
  {
    id: 'builtin-source-2f6848a57686',
    originalId: 'source-2f6848a57686',
    name: 'Organize Research by goals with a persistent center map and a resizable Codex or Claude conversation sidebar, and restor',
    description:
      'Organize Research by goals with a persistent center map and a resizable Codex or Claude conversation sidebar, and restore the selected Map label',
    version: '1.0.0',
    createdAt: '2026-10-09T05:06:59.966Z',
    updatedAt: '2026-10-09T05:06:59.966Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/ResearchLayout.tsx',
      'src/renderer/components/ResearchWorkbench.tsx',
      'src/renderer/components/SidebarResize.tsx',
      'src/renderer/components/header-view-switch.css',
      'src/renderer/components/research-agent-layout.css',
      'src/renderer/workbench.ts',
    ],
    features: ['research-workbench', 'sidebar-resizing'],
    effect:
      'Turning this extension off disables research navigation, machine synchronization and workspace lifecycle, sidebar resize controls.',
  },
  {
    id: 'builtin-source-deac6139f1b6',
    originalId: 'source-deac6139f1b6',
    name: 'Extend the Research agent sidebar through the title bar with an aligned, full-height resize divider',
    description:
      'Extend the Research agent sidebar through the title bar with an aligned, full-height resize divider',
    version: '1.0.0',
    createdAt: '2026-10-09T05:24:08.077Z',
    updatedAt: '2026-10-09T05:24:08.077Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/ResearchLayout.tsx',
      'src/renderer/components/research-agent-layout.css',
    ],
    features: ['research-fullheight'],
    effect: 'Turning this extension off disables research full-height sidebar styling.',
  },
  {
    id: 'builtin-source-9d9f38a237da',
    originalId: 'source-9d9f38a237da',
    name: 'Keep one New goal button beside Research search and fix the goal creation dialog',
    description: 'Keep one New goal button beside Research search and fix the goal creation dialog',
    version: '1.0.0',
    createdAt: '2026-10-09T05:30:34.724Z',
    updatedAt: '2026-10-09T05:30:34.724Z',
    files: [
      'src/renderer/components/ResearchWorkbench.tsx',
      'src/renderer/components/research-goal-controls.css',
    ],
    features: ['research-goal-controls'],
    effect: 'Turning this extension off disables compact research goal controls.',
  },
  {
    id: 'builtin-source-60cf7584c344',
    originalId: 'source-60cf7584c344',
    name: 'Machine-backed Research with editable maps, persistent conversation drafts, filters and sorting, and a collapsible unifi',
    description:
      'Machine-backed Research with editable maps, persistent conversation drafts, filters and sorting, and a collapsible unified sidebar',
    version: '1.0.0',
    createdAt: '2026-10-09T06:23:38.407Z',
    updatedAt: '2026-10-09T06:23:38.407Z',
    files: [
      'src/renderer/App.tsx',
      'src/renderer/components/GraphCanvas.tsx',
      'src/renderer/components/ResearchEditableMap.tsx',
      'src/renderer/components/ResearchLayout.tsx',
      'src/renderer/components/ResearchSidebarFilters.tsx',
      'src/renderer/components/ResearchWorkbench.tsx',
      'src/renderer/components/research-machine.css',
      'src/renderer/conversation-drafts.ts',
      'src/renderer/research-files.ts',
      'src/renderer/workbench.ts',
    ],
    features: ['research-workbench', 'persistent-drafts', 'research-filters'],
    effect:
      'Turning this extension off disables research navigation, machine synchronization and workspace lifecycle, automatic draft saving (saved drafts remain recoverable), research filter and sort controls.',
  },
  {
    id: 'builtin-source-3ed4505f113d',
    originalId: 'source-3ed4505f113d',
    name: 'Enable, disable, and delete built-in Life extensions',
    description: 'Enable, disable, and delete built-in Life extensions',
    version: '1.0.0',
    createdAt: '2026-10-09T14:54:52.706Z',
    updatedAt: '2026-10-09T14:54:52.706Z',
    files: ['src/renderer/builtin-extensions.ts', 'src/renderer/components/ExtensionDialog.tsx'],
    features: ['builtin-management-shortcut', 'extension-backups'],
    effect:
      'Turning this extension off disables the sidebar extension-management shortcut (recovery remains available from Life Studio), the full extension-backup export shortcut.',
  },
]

/** Overlapping historical extensions share execution gates; every required extension must be enabled. */
export function builtinFeatureEnabled(
  extensions: readonly SourceExtensionSummary[],
  feature: BuiltinFeatureKey,
): boolean {
  const owners = builtinExtensionCatalog.filter((extension) => extension.features.includes(feature))
  return owners.every((owner) => {
    const state = extensions.find((extension) => extension.builtIn && extension.id === owner.id)
    return !state || (state.enabled && !state.deleted)
  })
}

export function relatedBuiltinExtensions(id: string): readonly BuiltinExtensionDefinition[] {
  const selected = builtinExtensionCatalog.find((extension) => extension.id === id)
  if (!selected) return []
  return builtinExtensionCatalog.filter(
    (extension) =>
      extension.id !== id &&
      extension.features.some((feature) => selected.features.includes(feature)),
  )
}
