import { createResearchMethod, type ResearchMethod } from '../shared/research-method'

/** Public illustrative records. Nothing here is a measured result or a real user's research. */
export function createWebResearchExampleMethod(now: number): ResearchMethod {
  return {
    ...createResearchMethod(),
    requirements: [
      {
        id: 'example-whole',
        statement: 'Build a traceable research workflow',
        acceptance: 'Each chosen mechanism can be traced to a requirement and a recorded check.',
        rationale: 'Illustrative whole-level outcome.',
        kind: 'requirement',
        priority: 'essential',
        atomic: false,
        status: 'proposed',
        assumptionIds: [],
        evidenceIds: [],
        updatedAt: now,
      },
      {
        id: 'example-leaf-context',
        parentId: 'example-whole',
        statement: 'Keep each basic requirement independently testable',
        acceptance: 'Every leaf has one acceptance criterion that can fail.',
        rationale: 'Anti-abstraction exposes what the whole depends on.',
        kind: 'requirement',
        priority: 'essential',
        atomic: true,
        status: 'proposed',
        assumptionIds: ['example-assumption'],
        evidenceIds: [],
        updatedAt: now,
      },
      {
        id: 'example-leaf-interactions',
        parentId: 'example-whole',
        statement: 'Record the mechanism of every proposed combination',
        acceptance: 'Every composite names its contributors, joint effect, and a pending test.',
        rationale: 'Abstraction should explain how constituents form a whole.',
        kind: 'requirement',
        priority: 'essential',
        atomic: true,
        status: 'proposed',
        assumptionIds: [],
        evidenceIds: [],
        updatedAt: now,
      },
    ],
    assumptions: [
      {
        id: 'example-assumption',
        claim: 'Requirements can be decomposed into independently testable leaves.',
        challenge: 'Some goals may depend on coupled conditions that cannot be tested alone.',
        consequence: 'A falsely atomic leaf could hide an interaction or missing constraint.',
        status: 'unverified',
        requirementIds: ['example-leaf-context'],
        evidenceIds: [],
        updatedAt: now,
      },
    ],
    candidates: [
      {
        id: 'example-decomposition',
        title: 'Requirement tree',
        mechanism: 'Link each basic requirement to its parent and acceptance criterion.',
        risks: 'Over-decomposition can lose system-level effects.',
        componentCandidateIds: [],
        constituentIds: ['example-leaf-context'],
        emergence: '',
        status: 'proposed',
        requirementIds: ['example-leaf-context'],
        assumptionIds: ['example-assumption'],
        evidenceIds: [],
        updatedAt: now,
      },
      {
        id: 'example-journal',
        title: 'Interaction journal',
        mechanism: 'Record compatible and conflicting contributions as explicit hypotheses.',
        risks: 'A written relationship is not evidence that the combined mechanism works.',
        componentCandidateIds: [],
        constituentIds: ['example-leaf-interactions'],
        emergence: '',
        status: 'proposed',
        requirementIds: ['example-leaf-interactions'],
        assumptionIds: [],
        evidenceIds: [],
        updatedAt: now,
      },
      {
        id: 'example-composite',
        title: 'Traceable synthesis',
        mechanism:
          'Use the requirement tree to choose candidate mechanisms; use the journal to retain their joint effects and conflicts.',
        risks: 'The complete workflow still needs a realistic end-to-end experiment.',
        componentCandidateIds: ['example-decomposition', 'example-journal'],
        constituentIds: ['example-leaf-context', 'example-leaf-interactions'],
        emergence: 'A proposed whole connecting decomposition, composition, and verification.',
        status: 'proposed',
        requirementIds: ['example-leaf-context', 'example-leaf-interactions'],
        assumptionIds: ['example-assumption'],
        evidenceIds: [],
        updatedAt: now,
      },
    ],
    interactions: [
      {
        id: 'example-interaction',
        candidateIds: ['example-decomposition', 'example-journal'],
        kind: 'constructive',
        mechanism:
          'The tree exposes individual obligations; the journal exposes effects that appear only when those obligations are combined. This is an illustrative hypothesis, not a verified finding.',
        evidenceIds: [],
        updatedAt: now,
      },
    ],
    validations: [
      {
        id: 'example-check',
        title: 'Test the combined workflow',
        procedure:
          'Choose a real goal, decompose it, assemble two approaches, then inspect whether every required outcome has a check and every combination has a mechanism.',
        expected:
          'No essential leaf is uncovered and no composite is treated as proven without an observation.',
        actual: '',
        outcome: 'pending',
        requirementIds: ['example-leaf-context', 'example-leaf-interactions'],
        candidateIds: ['example-composite'],
        evidenceIds: [],
        updatedAt: now,
      },
    ],
    inquiries: [
      {
        id: 'example-counterfactual',
        operation: 'counterfactual',
        question: 'What breaks if the interaction journal is removed?',
        premise: 'The decomposition tree still exists.',
        intervention: 'Remove explicit records of joint effects.',
        prediction:
          'System-level conflicts may disappear from view while individual leaves still appear covered.',
        result: '',
        status: 'proposed',
        requirementIds: ['example-leaf-interactions'],
        candidateIds: ['example-composite'],
        evidenceIds: [],
        updatedAt: now,
      },
    ],
  }
}
